nome_da_maquina = input("digite o nome da maquina:")
valor_da_maquina = float(input("Digite o valor da maquina:"))
consumo_por_litro = float(input("digite o consumo do litro da maquina:"))
ano = float(input("ano:"))
print("-" * 25)
print(f"|maquina: {nome_da_maquina}")
print(f"|valor: R$ {valor_da_maquina}")
print(f"|consumo por litro: R$ {consumo_por_litro}")
print(f"|ano:  {ano}")
print("-" * 25)